import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/shared/Header";
import { Toaster } from "@/components/ui/toaster";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import dynamic from "next/dynamic";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const ReduxProvider = dynamic(() => import("@/redux/ReduxProvider"), {
  ssr: false,
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Header />
          {children}
          <Toaster />
        </ReduxProvider>
      </body>
    </html>
  );
}
